-- 1. What are the names of all the products available in the store?
select product_name 
from products;

-- 2. What is the total number of products in the store?
select count(*) as total_number_of_products 
from products;

-- 3. What are the different product categories available in the store?
select distinct product_name as different_product_categories 
from products;

-- 4. How much is the average price of a product in the store?
select cast(avg(product_price) as int) as average_price 
from products;

-- 5. What are the names of the products that cost more than $50?
select product_name 
from products 
where product_price > 50;

-- 6. What is the total number of orders placed in the store?
select count(order_id) as total_number_of_orders 
from orders;

-- 7. Who are the customers who have placed an order in the store?
select distinct customer_name 
from orders;

-- 8. What is the total number of orders placed by each customer?
select customer_name, count(order_id) 
from orders 
group by customer_name;

-- 9. What is the total revenue generated from orders placed in the store?
select sum(product_price * order_quantity) as total_revenue 
from products
join orders
on products.product_id = orders.product_id;

-- 10. What is the average revenue generated from an order in the store?
select cast(avg(product_price * order_quantity) as int) as average_revenue 
from products
join orders
on products.product_id = orders.product_id;

-- 11. What is the total number of orders placed for each product?
select product_name,sum(orders.order_quantity)
from orders
join products 
ON products.product_id = orders.product_id
group by product_name;

-- 12. What is the most ordered product in the store?
select products.product_name,sum(orders.order_quantity)
from products
join orders 
ON orders.product_id = products.product_id
group by products.product_name
order by sum(orders.order_quantity) desc
limit 1;

-- 13. What is the total number of orders placed on each day?
select order_date, count(order_id)
from orders
group by order_date;

-- 14. What is the total revenue generated on each day?
select order_date, sum(products.product_price*orders.order_quantity) as total_revenue
from orders
join products 
ON products.product_id = orders.order_id
group by order_date;

-- 15. What is the total revenue generated by each product category?
select products.product_category, sum(products.product_price*orders.order_quantity) as total_revenue 
from orders
join products 
ON products.product_id = orders.product_id
group by products.product_category;

-- 16. What is the total revenue generated by each customer?
select orders.customer_name, sum(products.product_price*orders.order_quantity) as total_revenue
from orders
join products 
ON products.product_id = orders.product_id
group by orders.customer_name;

-- 17. How many orders were placed for each product?
select products.product_name, sum(orders.order_quantity) as total_orders
from orders
join products 
ON products.product_id = orders.product_id
group by products.product_name;

-- 18. What is the average revenue generated by each order?
select cast(avg(products.product_price*orders.order_quantity) as int) as average_revenue
from products
join orders 
ON orders.product_id = products.product_id;

-- 19. What is the most popular product based on the number of orders placed?
select products.product_name, sum(orders.order_quantity) as total_orders
from products
join orders
on products.product_id = orders.product_id
group by products.product_name
order by total_orders desc 
limit 1;

-- 20. Which customer placed the most orders?
select customer_name, count(orders.order_id) as total_orders
from orders
group by orders.customer_name
order by total_orders desc
limit 1;

-- 21. On which day was the highest revenue generated?
select orders.order_date, sum(products.product_price*orders.order_quantity) as total_revenue
from orders
join products 
on orders.product_id = products.product_id
group by orders.order_date
order by total_revenue desc
limit 1;